# ==========================
#       Video Filters
# ==========================

# -------- RIFE --------
CTRL+i vf add vapoursynth="~~/vs/rife.vpy"; show-text "RIFE"

# ==========================
#         Clear
# ==========================
CTRL+o vf clr ""; show-text "Video filters cleared"
